---
title: "Déposer son compte rendu"
toc-title: "Dans cette page"
---

## Principe

La formation FOCUS demande, dans les conditions de validation, de remplir un formulaire web. Cette démarche permet de rendre compte des apports auprès des participant·es.

## Fonctionnement

Pour le thème 4 : 

- soit vous avez travaillé en solo, soit en équipe ;
- soit vous ou votre équipe avez produit un document, soit vous vous apprêtez simplement à compléter le formulaire sans dépôt de document.

Quelque soit votre situation, le formulaire web vous accompagne dans la récolte d'informations.

## Utilisation de vos données

Compléter le formulaire web fait partie des activités attendues dans le cadre de la formation.

Vos informations permettent de comprendre quels sont les contenus qui ont fait sens et quelles sont les perspectives de transfert à la pratique.

## Formulaire web

Le formulaire web est accessible via ce lien **[à venir]**.

Veuillez noter que si vous ou votre groupe avez une ressource à déposer, celle-ci devra être téléchargée sur notre espace Teams (consignes dans le formulaire web).