---
title: "PARTIE 1 - LA CUA"
navbar: true
toc-title: "Sur cette page"
---

## Capsules vidéos pour apprentissage en autonomie

**Période d'appropriation conseillée : entre le 4 et le 22 septembre 2023**

1. [Partie 1 sur 10](https://tube.switch.ch/videos/tfxAOO9T03)
1. [Partie 2 sur 10](https://tube.switch.ch/videos/kIqP6BFRSY)
1. [Partie 3 sur 10](https://tube.switch.ch/videos/VyJfZl85kY)
1. [Partie 4 sur 10](https://tube.switch.ch/videos/pVllgzAsms)
1. [Partie 5 sur 10](https://tube.switch.ch/videos/kdIsvXN7Sb)
1. [Partie 6 sur 10](https://tube.switch.ch/videos/gK7tHrnOiU)
1. [Partie 7 sur 10](https://tube.switch.ch/videos/2BVf1Sq7mL)
1. [Partie 8 sur 10](https://tube.switch.ch/videos/CwSrgb46iA)
1. [Partie 9 sur 10](https://tube.switch.ch/videos/JCKhgsYfiG)
1. [Partie 10 sur 10](https://tube.switch.ch/videos/kmKjTAVCHh)

## Communautés de pratiques - Fonctionnement recommandé

**Recommandation de minimum 2 rencontres avec des collègues de proximité participant à la formation. Réalisation libre.**

- [Proposition de canevas de fonctionnement pour votre première communauté de pratiques](https://hepvsch-my.sharepoint.com/:b:/g/personal/nicolas_bressoud_hepvs_ch/EftcC1eqw6BNuIAmS8G_NVgBqSyeHRnH_ecrguKng6RIvA?e=LuC4Pm)

- [Proposition de canevas de fonctionnement pour votre seconde communauté de pratiques](https://hepvsch-my.sharepoint.com/:b:/g/personal/nicolas_bressoud_hepvs_ch/ETqmZOBzMcBFtazeVbYISAIBVXMrIJYDGb5bJNzEHeRvew?e=lygD0k)

## Création d'une ressource - Fonctionnement recommandé

**Choix libre de la ou des ressource(s) à créer. Dans toute la formation FOCUS, une seule peut être déposée par communauté (pas par personne).**

**Ces documents ne sont utiles que si la communauté décide de déposer un document traitant de la CUA.**

- [Proposition de canevas pour publication d'une ressource (version Word modifiable)](https://hepvsch-my.sharepoint.com/:w:/g/personal/nicolas_bressoud_hepvs_ch/EWcVTfpkc8ZKt-cmGJ9WgcQBOzHcks_cx1ErWW1pe6DZOg?e=qFeMzl)

- [Proposition de canevas pour publication d'une ressource (version pour impression)](https://hepvsch-my.sharepoint.com/:b:/g/personal/nicolas_bressoud_hepvs_ch/ETqg_-PF3j5PmM6jpslSrdUBZoi1-6A1gMESxUkPCMUyCA?e=PqfyAW)
