---
title: "PARTIE 2 - PSE·R"
navbar: true
---

Voici un petit *teaser* pour vous permettre d'anticiper le contenu :

<iframe width="640" height="360" src="https://tube.switch.ch/embed/ey3PZxcDkD" frameborder="0" allow="fullscreen" allowfullscreen></iframe>

Le PSR·R est à voir en tant que démarche de soutien à la démarche PPI qui fait partie de la culture de l'enseignement spécialisé valaisan. le PSE·R est moins détaillé que le PPI. Cependant, il guide de manière explicite la réflexion et la mesure de **l'impact** du projet.

Alors que la CUA (Partie 1/2 du thème 4) propose des pistes pour la pédagogie de la classe ordinaire, le PSE·R (Partie 2/2 du thème 4)  soutient, dans le réseau, la résolution de problème et l'évaluation des progrès :

**Période d'appropriation conseillée : entre le 29 janvier et le 9 février 2024**

<!-- 1. [Partie 1 sur 9](https://tube.switch.ch/videos/lcrLbdEP6g) -->
<!-- 1. [Partie 2 sur 9](https://tube.switch.ch/videos/5xnk341YBN) -->
<!-- 1. [Partie 3 sur 9](https://tube.switch.ch/videos/7XJkaKKvLg) -->
<!-- 1. [Partie 4 sur 9](https://tube.switch.ch/videos/I9DfmUroSh) -->
<!-- 1. [Partie 5 sur 9](https://tube.switch.ch/videos/k1NGuC2WJj) -->
<!-- 1. [Partie 6 sur 9](https://tube.switch.ch/videos/PRDxBxd7NF) -->
<!-- 1. [Partie 7 sur 9](https://tube.switch.ch/videos/evnuxOkcgQ) -->
<!-- 1. [Partie 8 sur 9](https://tube.switch.ch/videos/UCG6EQ9oBb) -->
<!-- 1. [Partie 9 sur 9](https://tube.switch.ch/videos/i9hAc4woXx) -->

 A VENIR.

## Création d'une ressource - Fonctionnement

**Choix libre de la ou des ressource(s) à créer. Dans toute la formation FOCUS, une seule peut être déposée par communauté (pas par personne).**

**Ces documents ne sont utiles que si la communauté décide de déposer un document traitant du processus PSE·R**

<!-- - [Proposition de canevas pour publication d'une ressource (version PDF)](https://hepvsch-my.sharepoint.com/:b:/g/personal/nicolas_bressoud_hepvs_ch/ESonlRi2m7RCm6ZgPIfYl_kBk_9kltbTxKvvCKhplSpZaQ?e=Y0yJ0V) -->

A VENIR


